# Working with ordered inserts

Em se tratando de objetos com ids próprios, ou seja, ids criados por nós e não usando o _objectId_ criado pelo próprio mongo, podemos declarar, na criação do objeto através da palavra chave `_id` por exemplo:

```JavaScript
> use ContactData
> db.hobbies.insertMany(
	[
		{_id: "sports", name: "Sports"},
		{_id: "cooking", name: "Cooking"},
		{_id: "cars", name: "Cars"}
	]
)
```

Como resultado temos, ao contrário dos _objectsIds_ temos:

```JavaScript
{
  acknowledged: true,
  insertedIds: { '0': 'sports', '1': 'cooking', '2': 'cars' }
}
```

Se tentarmos inserir novos objetos com ids próprios e por um acaso não lembrarmos quais objetos inserimos na última ocasião e acabarmos tentando inserir um objeto com mesmo `_id` teremos o seguinte resultado:

```JavaScript
> use ContactData
> db.hobbies.insertMany(
	[
		{_id: "yoga", name: "Yoga"},
		{_id: "cooking", name: "Cooking"},
		{_id: "hicking", name: "Hicking"}
	]
)
```

```JavaScript
MongoBulkWriteError: E11000 duplicate key error collection: contactData.hobbies index: _id_ dup key: { _id: "cooking" }
Result: BulkWriteResult {
  result: {
    ok: 1,
    writeErrors: [
      WriteError {
        err: {
          index: 1,
          code: 11000,
          errmsg: 'E11000 duplicate key error collection: contactData.hobbies index: _id_ dup key: { _id: "cooking" }',
          errInfo: undefined,
          op: { _id: 'cooking', name: 'Cooking' }
        }
      }
    ],
    writeConcernErrors: [],
    insertedIds: [
      { index: 0, _id: 'yoga' },
      { index: 1, _id: 'cooking' },
      { index: 2, _id: 'hicking' }
    ],
    nInserted: 1,
    nUpserted: 0,
    nMatched: 0,
    nModified: 0,
    nRemoved: 0,
    upserted: []
  }
}
```

Aqui temos o seguinte erro `MongoBulkWriteError: E11000 duplicate key error collection: contactData.hobbies index: _id_ dup key: { _id: "cooking" }`, indicando que houve um erro na inserção pois consta uma objeto com `_id` duplicado. O mongo ainda indica qual o `_id`.

Nessa parte do código indica que apenas 1 documento foi inserido.
```JavaScript
nInserted: 1,
nUpserted: 0,
nMatched: 0,
nModified: 0,
nRemoved: 0,
upserted: []
```

Utilizando o comando `db.hobbies.find()` temos o resultado do que já foi inserido:

```JavaScript
[
  { _id: 'sports', name: 'Sports' },
  { _id: 'cooking', name: 'Cooking' },
  { _id: 'cars', name: 'Cars' },
  { _id: 'yoga', name: 'Yoga' }
]
```

Ou seja apenas o primeiro item do último `insertMany` foi gravado. O segundo item foi o que gerou o erro e o terceiro, apesar de ser novo e ter um `_id` único não foi inserido. 

> [!Important]
> Por padrão o Mongo possui esse comportamento e é chamado de _Ordered Insert_ (Inserção Ordenada), significando que todo elemento que inserido é processado um por um, mas se um falhar, toda a operação restante é cancelada mas não reverterá os elementos que já foram inseridos. 

Existe a possibilidade de alterar esse comportamento, utilizando os mesmos dados que na tentativa anterior, que agora falhará já no inicio, uma vez que o primeiro elemento _yoga_ já foi inserido no banco de dados, podemos passar um segundo documento dentro da função `insertMany`, que configurará a operação. 

Existem algumas opções que podemos passar nesse documento como `ordered` que por padrão está configurado como `true`, portanto passar o valor `True` será redundante, mas se passarmos `false` teremos o seguinte resultado:

```JavaScript
> db.hobbies.insertMany(
	[
		{_id: "yoga", name: "Yoga"},
		{_id: "cooking", name: "Cooking"},
		{_id: "hicking", name: "Hicking"}
	],
	{ordered: false}
)
```

```JavaScript
MongoBulkWriteError: E11000 duplicate key error collection: contactData.hobbies index: _id_ dup key: { _id: "yoga" }
Result: BulkWriteResult {
  result: {
    ok: 1,
    writeErrors: [
      WriteError {
        err: {
          index: 0,
          code: 11000,
          errmsg: 'E11000 duplicate key error collection: contactData.hobbies index: _id_ dup key: { _id: "yoga" }',
          errInfo: undefined,
          op: { _id: 'yoga', name: 'Yoga' }
        }
      },
      WriteError {
        err: {
          index: 1,
          code: 11000,
          errmsg: 'E11000 duplicate key error collection: contactData.hobbies index: _id_ dup key: { _id: "cooking" }',
          errInfo: undefined,
          op: { _id: 'cooking', name: 'Cooking' }
        }
      }
    ],
    writeConcernErrors: [],
    insertedIds: [
      { index: 0, _id: 'yoga' },
      { index: 1, _id: 'cooking' },
      { index: 2, _id: 'hicking' }
    ],
    nInserted: 1,
    nUpserted: 0,
    nMatched: 0,
    nModified: 0,
    nRemoved: 0,
    upserted: []
  }
}
```

Aqui temos 1 erro, indicando que há `_id` duplicado, mas também indica os dois objetos cujo o `_id` já existem. Além disso temos como resultado que 1 documento foi inserido. 

```JavaScript
nInserted: 1,
nUpserted: 0,
nMatched: 0,
nModified: 0,
nRemoved: 0,
upserted: []
```

```JavaScript
> db.hobbies.find()
[
  { _id: 'sports', name: 'Sports' },
  { _id: 'cooking', name: 'Cooking' },
  { _id: 'cars', name: 'Cars' },
  { _id: 'yoga', name: 'Yoga' },
  { _id: 'hicking', name: 'Hicking' }
]
```

## Conclusão

O Mongo não reverte as operações bem sucedidas mesmo que a inserção de algum documento falhe. Utilizando o `ordered: false` podemos configurar o `insertMany` para inserir todos os outros documentos, que não possuem `_id` idêntico no banco de dados, mesmo havendo na lista documento já existentes. 

